name: Release Assets

# Manually release assets if failed on automatic release
# See issue #19 for details

on:
  workflow_dispatch:

env:
  RELEASE_TAG: v0.1.10
  RUN_ID: 2167621475
  COMMIT_SHA: 275579c93fd1d89900dd44056af445daa91380d3

jobs:
  # Test release on GitHub
  # Used to test issue #19
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v2
      # Download deployments from build artifacts
      - name: Download deployment artifact (Ubuntu py3.6)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: release.yml
          run_id: ${{ env.RUN_ID }}
          branch: main
          name: deployment-ubuntu-20.04-py${{ matrix.python-version }}-${{ env.COMMIT_SHA }}-pyphase-release
          path: deployment
      - name: Upload Linux wheel release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            deployment/phase*linux_x86_64.whl

  cleanup-deployments:
      needs: [deploy]
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-20.04]
          python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

      steps:
        - uses: geekyeggo/delete-artifact@v1
          with:
            name: deployment-${{ matrix.os }}-py${{ matrix.python-version }}-${{ github.sha }}-pyphase-release