name: Test Release

on:
  workflow_dispatch:

jobs:
  # Test release on GitHub
  # Used to test issue #19
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      # Download deployments from build artifacts
      - name: Download deployment artifact (Ubuntu py3.6)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: release.yml
          run_id: 2167621475
          branch: main
          name: deployment-ubuntu-20.04-py3.10-275579c93fd1d89900dd44056af445daa91380d3-pyphase-release
          path: deployment
      - name: Upload Linux wheel release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.10
          files: |
            deployment/phase*linux_x86_64.whl
